parameters:
    select_ary:
        0: {id: 'user_id', attribute: 'USER_ID', filter: false, cpf: false}
        1: {id: 'user_type', attribute: 'USER_TYPE', filter: false, cpf: false}
        2: {id: 'group_id', attribute: 'USER_GROUP', filter: false, cpf: false}
        3: {id: 'user_lang', attribute: 'USER_LANG', filter: true, cpf: false}
        4: {id: 'user_timezone', attribute: 'USER_TIMEZONE', filter: false, cpf: false}
        5: {id: 'user_birthday', attribute: 'USER_BIRTHDAY', filter: false, cpf: false}
        7: {id: 'user_ip', attribute: 'USER_IP', filter: false, cpf: false}
        8: {id: 'user_dateformat', attribute: 'USER_DATE_FORMAT', filter: false, cpf: false}
        9: {id: 'user_style', attribute: 'USER_STYLE', filter: false, cpf: false}
        10: {id: 'user_rank', attribute: 'USER_RANK', filter: false, cpf: false}
        11: {id: 'user_avatar', attribute: 'USER_AVATAR', filter: false, cpf: false}
        12: {id: 'user_avatar_type', attribute: 'USER_AVATAR_TYPE', filter: false, cpf: false}
        13: {id: 'user_sig', attribute: 'USER_SIG', filter: false, cpf: false}
        14: {id: 'user_email', attribute: 'USER_EMAIL', filter: true, cpf: false}
        15: {id: 'user_jabber', attribute: 'USER_JABBER', filter: true, cpf: false}
        16: {id: 'user_regdate', attribute: 'USER_REGDATE', filter: false, cpf: false}
        17: {id: 'user_passchg', attribute: 'USER_PASS_CHANGE', filter: false, cpf: false}
        18: {id: 'user_lastvisit', attribute: 'USER_LASTVISIT', filter: false, cpf: false}
        19: {id: 'user_lastmark', attribute: 'USER_LASTMARK', filter: false, cpf: false}
        20: {id: 'user_lastpost_time', attribute: 'USER_LASTPOST_TIME', filter: false, cpf: false}
        21: {id: 'user_lastpage', attribute: 'USER_LAST_PAGE', filter: false, cpf: false}
        22: {id: 'user_last_search', attribute: 'USER_LAST_SEARCH', filter: false, cpf: false}
        23: {id: 'user_warnings', attribute: 'USER_WARNINGS', filter: false, cpf: false}
        24: {id: 'user_last_warning', attribute: 'USER_LAST_WARNING', filter: false, cpf: false}
        25: {id: 'user_login_attempts', attribute: 'USER_LOGIN_ATTEMPTS', filter: false, cpf: false}
        26: {id: 'user_inactive_reason', attribute: 'USER_INACTIVE_REASON', filter: false, cpf: false}
        27: {id: 'user_inactive_time', attribute: 'USER_INACTIVE_TIME', filter: false, cpf: false}
        28: {id: 'user_posts', attribute: 'USER_POSTS', filter: false, cpf: false}
        29: {id: 'user_new_privmsg', attribute: 'USER_NEW_PRIVMSG', filter: true, cpf: false}
        30: {id: 'user_unread_privmsg', attribute: 'USER_UNREAD_PRIVMSG', filter: true, cpf: false}
        31: {id: 'user_last_privmsg', attribute: 'USER_LAST_PRIVMSG', filter: true, cpf: false}
        32: {id: 'user_emailtime', attribute: 'USER_EMAILTIME', filter: true, cpf: false}
        33: {id: 'user_notify', attribute: 'USER_NOTIFY', filter: false, cpf: false}
        34: {id: 'user_notify_pm', attribute: 'USER_NOTIFY_PM', filter: false, cpf: false}
        35: {id: 'user_notify_type', attribute: 'USER_NOTIFY_TYPE', filter: false, cpf: false}
        36: {id: 'user_allow_pm', attribute: 'USER_ALLOW_PM', filter: false, cpf: false}
        37: {id: 'user_allow_viewonline', attribute: 'USER_ALLOW_VIEWONLINE', filter: false, cpf: false}
        38: {id: 'user_allow_viewemail', attribute: 'USER_ALLOW_VIEWEMAIL', filter: false, cpf: false}
        39: {id: 'user_allow_massemail', attribute: 'USER_ALLOW_MASSEMAIL', filter: false, cpf: false}