-- 20/06/2020 - Adding config for columns of products list on frontend for page
ALTER TABLE `pages` ADD `config` TEXT NULL AFTER `page_template`;

CREATE TABLE IF NOT EXISTS `menus` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `code` varchar(100) NOT NULL,
  `description` varchar(255) NULL,
  `items` text null,
  `created_dtm` datetime NOT NULL,
  `modified_dtm` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `menus` (`id`, `name`, `code`, `description`, `items`, `created_dtm`, `modified_dtm`) VALUES (NULL, 'Menu category', 'category-menu', NULL, '[{"text":"All Menu","short_text":"Menu","en_text":"Menu","page":"menu","href":"http://www.efruit.loc/vi/menu","target":"_self","cat":"1","description":"Trang đặt hàng có tất cả sản phẩm của eFruit","image":"//www.efruit.vn/uploads/menu-all.jpg"},{"text":"Trái cây cắt","short_text":"Freshly Cut","en_text":"Freshly Cut","page":"trai-cay-cat","href":"http://www.efruit.loc/vi/trai-cay-cat","target":"_self","cat":"","description":"Trái cây cắt tươi ngon, tiện lợi dùng cho các buổi họp, event, training, happy hous công ty. Để đảm bảo tươi ngon, khi có yêu cầu đặt hàng của quý khách chúng tôi mới cắt","image":"//www.efruit.vn/uploads/fresly-cut.jpg"},{"text":"Thức uống trái cây","short_text":"Healthy Drink","en_text":"Healthy Drink","page":"thuc-uong","href":"http://www.efruit.loc/vi/thuc-uong","target":"_self","cat":"","description":"Các sản phẩm Nước ép nguyên chất, Sinh tố từ 100% trái cây, rau củ tươi ngon an toàn tốt cho sức khỏe","image":"//www.efruit.vn/uploads/healthy-drink.jpg"},{"text":"Bánh tiệc, tea break và ăn vặt","short_text":"Cakes","en_text":"Cakes, tea break","page":"banh-tiec","href":"http://www.efruit.loc/vi/banh-tiec","target":"_self","cat":"","description":"Bánh ngon và lành được làm từ các đầu bếp tài ba, đáp ứng cho nhu cầu ăn vặt lành mạnh và các tiệc Tea Break, tổ chức sinh nhật nội bộ, họp, event...","image":"//www.efruit.vn/uploads/cake.jpg"},{"text":"Trái cây bán kg","short_text":"Fresh Fruit","en_text":"Fresh Fruit","page":"trai-cay-kg","href":"http://www.efruit.loc/vi/trai-cay-kg","target":"_self","cat":"","description":"Trái cây tươi an toàn, thu từ vườn cung cấp đến khách hàng với tiêu chuẩn VietGap, Globalgal, các vườn hướng hữu cơ, hữu cơ","image":"//www.efruit.vn/uploads/fresh-fruit.jpg"},{"text":"Trái cây theo gói","short_text":"Fruit Box","en_text":"Fruit Box","page":"hop-trai-cay","href":"http://www.efruit.loc/vi/hop-trai-cay","target":"_self","cat":"","description":"Các giải pháp trái cây tươi đến mọi nhà, văn phòng với chi phí hợp lý, nhiều ưu đãi hấp dẫn","image":"//www.efruit.vn/uploads/square-small/fruit-box.jpg"}]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `menus` (`id`, `name`, `code`, `description`, `items`, `created_dtm`, `modified_dtm`) VALUES (NULL, 'Menu top', 'main-menu', NULL, '[{"text":"Trang chủ","short_text":"Trang chủ","en_text":"Home","page":"trang-chu","href":"http://www.efruit.loc/vi/trang-chu","target":"_self","cat":"","description":"","image":""},{"text":"Về eFruit","short_text":"Về eFruit","en_text":"About us","page":"gioi-thieu","href":"http://www.efruit.loc/vi/gioi-thieu","target":"_self","cat":"","description":"","image":""},{"text":"Tin Tức","short_text":"Tin Tức","en_text":"News","page":"","href":"/vi/tin-tuc","target":"_self","cat":"","description":"","image":""},{"text":"Thành viên","short_text":"Thành viên","en_text":"Members","page":"uu-dai-thanh-vien","href":"http://www.efruit.loc/vi/uu-dai-thanh-vien","target":"_self","cat":"","description":"","image":""}]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `menus` (`id`, `name`, `code`, `description`, `items`, `created_dtm`, `modified_dtm`) VALUES (NULL, 'Menu footer 1', 'footer-menu-1', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `menus` (`id`, `name`, `code`, `description`, `items`, `created_dtm`, `modified_dtm`) VALUES (NULL, 'Menu footer 2', 'footer-menu-2', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);