<?php
$e_config = [
    'MYSQL_HOST' => 'localhost',
    'MYSQL_DBNAME' => 'efruit_db',
    'MYSQL_USER' => 'efruit_db',
    'MYSQL_PASS' => '********',
    'VERSION' => '5.0',
    'DB_VERSION' => '12.5',
    'ASSET_UPDATED_DATE' => '20210313',
    'ITEMS_PER_PAGE' => 50,
    'DEFAULT_LAT' => '10.805838',
    'DEFAULT_LNG' => '106.66616',
    'MAX_TIMES_TO_DO_ASSESSMENT_LATE' => 3,
    'WARNING_QUANTITY' => 3,
    'NUMBER_OF_ITEMS_PER_PAGE' => 8,
    'ACTIVE_THEME' => 'efruit',
    'CHILD_THEME' => '',
    'USING_SAME_PRICE' => 1,
    'ADMIN_EMAIL' => 'mik.hien.do@gmail.com',
    'SYSTEM_EMAIL' => 'hethong@efruit.vn',
    'SHIFT_SEPARATOR_TIME' => '17:30',
    'SSO_FORUM' => 0,
    'GA_ID' => 'UA-42643123-1',
    'TIDIO_ID' => 'oad7aakcwalvnr5sricbibisxmoja5og',
    'ACTIVE_PROJECT' => 'efruit',
    'SEND_CUSTOMER_EMAIL_TO_DEV' => 0,
    'DOMAIN_NAME' => 'efruit.vn' /* Do not set to get current domain */,
    'START_YEAR' => '2013',
    'NEED_BOOKER_DETAILS' => 1,
    'GOV_LINK' => '',
    'PREORDER_TIME' => array(
        'start' => '07:30',
        'end' => '22:00'
    ),
    'GROUP1_USER_IDS' => array(159, 156, 168),
    'GROUP2_USER_IDS' => array(61),
    'SALES_GROUP_USER_IDS' => array(79, 168),
    'DESIGN_GROUP_USER_IDS' => array(80),
    'PUBLIC_GROUP_USER_IDS' => array(154, 158),
    'GMAP_API_KEY' => 'AIzaSyB4tmVxcWyfYgq2rGQZSwe7XP4PbXJ58s4'
];
?>